# -*- coding: utf-8 -*-
"""schemas_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10mBnbu3w4S5w9nwWvh2PtmxUwuEFq6Sp
"""

from typing import Any, Literal
from pydantic import BaseModel, Field

SourceName = Literal["youtube", "naver_news", "naver_blog"]

class AnalyzeRequest(BaseModel):
    keyword: str
    sources: list[SourceName] = Field(default_factory=lambda: ["youtube", "naver_news", "naver_blog"])
    analysis_days: int = Field(default=30, ge=1, le=365)
    collection_days: int = Field(default=90, ge=1, le=365)
    include_related: bool = True
    trend_type: str = Field(default="F&B", description="업종 카테고리 (예: F&B, Fashion, IT)") # 💡 NEW
    limits: dict[str, int] = Field(default_factory=dict)
    save: bool = True

class ReanalyzeRequest(BaseModel):
    selected_sources: list[SourceName] | None = None
    analysis_days: int = Field(default=30, ge=1, le=365)
    include_related: bool = True
    trend_type: str = Field(default="F&B") # 💡 NEW
    save: bool = True

class RecollectRequest(BaseModel):
    keyword_set: dict[str, Any]
    sources: list[SourceName] = Field(default_factory=lambda: ["youtube", "naver_news", "naver_blog"])
    analysis_days: int = Field(default=30, ge=1, le=365)
    collection_days: int = Field(default=90, ge=1, le=365)
    include_related: bool = True
    trend_type: str = Field(default="F&B") # 💡 NEW
    limits: dict[str, int] = Field(default_factory=dict)
    save: bool = True