# -*- coding: utf-8 -*-
"""analyzer_router_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SDhV81Zk29zX8sY9kBd6c3wIIKXigKAz
"""

import json
from pathlib import Path
import pandas as pd


from .dashboard_packager_v5 import build_dashboard_data
from .feature_builder_v5 import build_trend_features, build_trend_index
from .raw_loader_v5 import filter_raw, load_run_raw
from .time_series_v5 import (
    build_keyword_set_daily_metrics,
    build_source_breakdown,
    build_term_breakdown,
    build_term_daily_metrics,
    build_weekly_partition,
)
from .ts_scorer_v5 import calculate_ts

PROJECT_ROOT = Path(__file__).resolve().parents[1]

def run_e3_analysis(
    run_dir: str,
    selected_sources: list[str] | None = None,
    analysis_days: int = 30,
    include_related: bool = True,
    trend_type: str = "F&B",  # 💡 [v5 핵심 추가] 업종 태그를 외부에서 받아옴
    save: bool = True,
) -> dict:
    run_path = Path(run_dir)
    run_id = run_path.name

    raw_df, run_meta = load_run_raw(str(run_path))
    run_meta["run_id"] = run_meta.get("run_id") or run_id
    canonical_keyword = run_meta.get("keyword_set", {}).get("canonical") or run_meta.get("keyword", "")
    available_sources = sorted(raw_df["source"].dropna().astype(str).unique().tolist())
    requested_sources = selected_sources if selected_sources is not None else available_sources
    missing_sources = sorted(set(requested_sources) - set(available_sources))

    warnings = build_warnings(
        selected_sources=requested_sources,
        missing_sources=missing_sources,
        analysis_days=analysis_days,
        include_related=include_related,
    )

    # 💡 [v5 핵심 연동] 하위 모듈로 쏴줄 옵션 딕셔너리에 trend_type 추가
    analysis_options = {
        "selected_sources": requested_sources,
        "analysis_days": analysis_days,
        "include_related": include_related,
        "trend_type": trend_type,  # <- 이 값이 모든 v5 로직을 가변적으로 만듦
        "date_basis": "published_at",
        "period_anchor": "max_published_at_in_filtered_data",
        "rerun_policy": "reanalyze_only",
    }

    filtered_raw = filter_raw(raw_df, selected_sources, analysis_days, include_related)
    period_start, period_end = get_analysis_period(filtered_raw, analysis_days)

    # 💡 [v5 파라미터 전달] 새로 만든 analysis_options를 각 함수에 주입
    term_daily = build_term_daily_metrics(filtered_raw, analysis_options=analysis_options)
    keyword_daily = build_keyword_set_daily_metrics(
        term_daily,
        canonical_keyword,
        start_date=period_start,
        end_date=period_end,
        analysis_options=analysis_options,
    )
    weekly_partition = build_weekly_partition(filtered_raw, analysis_options=analysis_options)
    source_breakdown = build_source_breakdown(filtered_raw)
    term_breakdown = build_term_breakdown(filtered_raw)

    # 💡 [버그 수정 1] build_trend_index는 (term_daily, keyword_daily) 두 개를 받음
    trend_index = build_trend_index(term_daily, keyword_daily)

    # 💡 [버그 수정 2] 인자 순서 바로잡기 (기존: keyword_daily, trend_index, weekly_partition -> 에러 유발)
    trend_features = build_trend_features(
        keyword_daily=keyword_daily,
        weekly_partition=weekly_partition,
        trend_index=trend_index,
        analysis_options=analysis_options
    )

    ts_result = calculate_ts(trend_features, analysis_options=analysis_options)

    if filtered_raw.empty:
        ts_result = {
            "ts_score": 0,
            "growth_score": 0,
            "reaction_score": 0,
            "saturation_score": 0,
            "decline_risk": 0,
            "formula_version": "TS_v5_empty",
            "status_label": "Low",
        }

    dashboard_data = build_dashboard_data(
        run_meta=run_meta,
        filtered_raw=filtered_raw,
        term_daily=term_daily,
        keyword_daily=keyword_daily,
        weekly_partition=weekly_partition,
        trend_index=trend_index,
        trend_features=trend_features,
        ts_result=ts_result,
        source_breakdown=source_breakdown,
        term_breakdown=term_breakdown,
        analysis_options=analysis_options,
        available_sources=available_sources,
        missing_sources=missing_sources,
        warnings=warnings,
    )

    if save:
        save_outputs(
            run_id=run_id,
            filtered_raw=filtered_raw,
            term_daily=term_daily,
            keyword_daily=keyword_daily,
            weekly_partition=weekly_partition,
            trend_features=trend_features,
            trend_index=trend_index,
            ts_result=ts_result,
            dashboard_data=dashboard_data,
        )

    return dashboard_data


def build_warnings(
    selected_sources: list[str],
    missing_sources: list[str],
    analysis_days: int,
    include_related: bool,
) -> list[str]:
    warnings = [
        "분석 기간은 수집 데이터의 최신 발행일(published_at)을 기준으로 계산됩니다. API 제공사 검색 결과가 오늘까지의 데이터를 항상 포함하지 않을 수 있습니다."
    ]
    if missing_sources:
        warnings.append(
            f"선택한 source 중 현재 run에 없는 채널이 있습니다: {', '.join(missing_sources)}. 해당 채널을 보려면 재수집이 필요합니다."
        )
    if not selected_sources:
        warnings.append("선택된 source가 없습니다.")
    if analysis_days <= 0:
        warnings.append("analysis_days가 0 이하입니다. 기간 필터가 의도와 다를 수 있습니다.")
    if not include_related:
        warnings.append("연관 키워드(term_type=related)를 제외한 핵심 키워드 기준 분석입니다.")
    return warnings


def get_analysis_period(filtered_raw: pd.DataFrame, analysis_days: int) -> tuple[str | None, str | None]:
    if filtered_raw.empty or not analysis_days:
        return None, None
    observed_start = filtered_raw["published_at"].min().date()
    observed_end = filtered_raw["published_at"].max().date()
    requested_start = observed_end - pd.Timedelta(days=analysis_days - 1)
    period_start = max(observed_start, requested_start)
    return period_start.isoformat(), observed_end.isoformat()


def save_outputs(
    run_id: str,
    filtered_raw: pd.DataFrame,
    term_daily: pd.DataFrame,
    keyword_daily: pd.DataFrame,
    weekly_partition: pd.DataFrame,
    trend_features: dict,
    trend_index: pd.DataFrame,
    ts_result: dict,
    dashboard_data: dict,
) -> None:
    processed_dir = PROJECT_ROOT / "data" / "processed" / run_id
    results_dir = PROJECT_ROOT / "data" / "results" / run_id
    processed_dir.mkdir(parents=True, exist_ok=True)
    results_dir.mkdir(parents=True, exist_ok=True)

    filtered_raw.to_csv(processed_dir / "filtered_raw.csv", index=False, encoding="utf-8-sig")
    term_daily.to_csv(processed_dir / "term_daily_metrics.csv", index=False, encoding="utf-8-sig")
    keyword_daily.to_csv(processed_dir / "keyword_set_daily_metrics.csv", index=False, encoding="utf-8-sig")
    weekly_partition.to_csv(processed_dir / "weekly_partition.csv", index=False, encoding="utf-8-sig")
    pd.DataFrame([trend_features]).to_csv(processed_dir / "trend_features.csv", index=False, encoding="utf-8-sig")

    trend_index.to_csv(results_dir / "trend_index.csv", index=False, encoding="utf-8-sig")
    write_json(results_dir / "ts_score.json", ts_result)
    write_json(results_dir / "dashboard_data.json", dashboard_data)


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


if __name__ == "__main__":
    default_run = PROJECT_ROOT / "data" / "raw"
    print("Run E3 with:")
    print("from analyzer_v5 import run_e3_analysis")
    print("run_e3_analysis('path/to/data/raw/run_xxx', trend_type='Fashion')")