# -*- coding: utf-8 -*-
"""dashboard_packager_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yf6Rljv2Wt0C_5IDCvczAoOwz1Tfe42
"""

import pandas as pd

def build_dashboard_data(
    run_meta: dict,
    filtered_raw: pd.DataFrame,
    term_daily: pd.DataFrame,
    keyword_daily: pd.DataFrame,
    weekly_partition: pd.DataFrame,
    trend_index: pd.DataFrame,
    trend_features: dict,
    ts_result: dict,
    source_breakdown: list[dict],
    term_breakdown: list[dict],
    analysis_options: dict | None = None,
    available_sources: list[str] | None = None,
    missing_sources: list[str] | None = None,
    warnings: list[str] | None = None,
) -> dict:
    analysis_options = analysis_options or {}
    available_sources = available_sources or []
    missing_sources = missing_sources or []
    warnings = warnings or []

    if filtered_raw.empty:
        warnings = [
            *warnings,
            "선택한 조건에 해당하는 수집 데이터가 없습니다.",
        ]

    last_updated = ""
    if not filtered_raw.empty and filtered_raw["published_at"].notna().any():
        last_updated = filtered_raw["published_at"].max().date().isoformat()

    # 💡 [피드백 반영] build_rule_report에 analysis_options와 term_breakdown을 넘겨줌
    rule_report = build_rule_report(
        ts_result=ts_result,
        trend_features=trend_features,
        source_breakdown=source_breakdown,
        term_breakdown=term_breakdown,       # NEW: 트렌드 부상 이유 분석용
        analysis_options=analysis_options,   # NEW: 업종별 동적 텍스트용
        is_empty=filtered_raw.empty
    )

    return {
        "run_id": run_meta.get("run_id"),
        "keyword": run_meta.get("keyword") or run_meta.get("keyword_set", {}).get("canonical", ""),
        "keyword_set": run_meta.get("keyword_set", {}),
        "keyword_set_mode": run_meta.get("keyword_set_mode", "preset"),
        "last_updated": last_updated,
        "analysis_options": analysis_options,
        "available_sources": available_sources,
        "missing_sources": missing_sources,
        "warnings": warnings,
        "ts_score": ts_result,
        "trend_features": trend_features,
        "rule_report": rule_report,            # 업그레이드된 브리핑 텍스트
        "trend_index_chart": trend_index.to_dict(orient="records"),
        "daily_metrics_chart": keyword_daily.to_dict(orient="records"),
        "weekly_metrics_chart": weekly_partition.to_dict(orient="records"),
        "source_breakdown": source_breakdown,
        "term_breakdown": term_breakdown,
    }


def build_rule_report(
    ts_result: dict,
    trend_features: dict,
    source_breakdown: list[dict],
    term_breakdown: list[dict],            # NEW
    analysis_options: dict,                # NEW
    is_empty: bool,
) -> dict:
    if is_empty:
        return {
            "summary": "선택한 조건에 해당하는 수집 데이터가 없습니다.",
            "evidence": "source, period, related 옵션을 조정하거나 새로 수집해보세요.",
            "drivers": "데이터 부족으로 견인 요소를 분석할 수 없습니다.",
            "risk": "데이터가 없어 하락 위험을 판단하지 않습니다.",
            "recommendation": "필터를 완화하거나 키워드 세트를 수정한 뒤 재수집할 수 있습니다.",
        }

    # 업종 옵션 로드
    trend_type = analysis_options.get("trend_type", "F&B")
    is_fb = (trend_type == "F&B")
    window_size = 7 if is_fb else 14 # 샤프 지수 계산에 쓴 기간 연동

    status = ts_result.get("status_label", "Watch")
    ts_score = ts_result.get("ts_score", 0)
    action_insight = ts_result.get("action_insight", "특별한 액션 제안이 없습니다.")

    sharpe_ratio = trend_features.get("sharpe_ratio", 0)
    ema_cross = trend_features.get("ema_cross", "none")
    top_source = source_breakdown[0]["source"] if source_breakdown else "분석 불가"

    # 1. 요약 (Summary): 현재 상태 선언
    summary = f"현재 트렌드 스코어는 {ts_score}점, 국면은 [{status}] 단계입니다."

    # 2. 근거 (Evidence): 하드코딩된 '최근 7일'을 동적 기간(window_size)으로 변경
    cross_text = "상승 돌파(골든크로스)" if ema_cross == "golden_cross" else "하락 반전(데드크로스)" if ema_cross == "death_cross" else "특이점 없음"
    evidence = (
        f"최근 {window_size}일 트렌드 안정성(샤프 지수)은 {sharpe_ratio}이며, 단기/장기 모멘텀 교차점은 '{cross_text}' 상태입니다. "
        f"가장 확산이 활발한 소스는 '{top_source}'입니다."
    )

    # 💡 3. [피드백 반영] 트렌드 부상 이유 (Drivers) 가시화 추가
    # term_breakdown에서 'related'(연관어) 타입 중 가장 비중이 높은 상위 2개를 추출
    top_related_terms = [
        t["term"] for t in term_breakdown
        if t.get("term_type") == "related"
    ][:2]

    if top_related_terms:
        drivers = f"현재 해당 키워드의 트렌드를 견인하는 주요 연관 이슈는 '{', '.join(top_related_terms)}'입니다."
    else:
        drivers = "현재 뚜렷하게 확산을 견인하는 특정 연관 키워드는 감지되지 않았습니다."

    # 💡 4. 리스크 (Risk): 업종에 따른 동적 경고 텍스트
    risk_action = "식자재 재고 소진에 유의하세요." if is_fb else "무리한 발주나 예산 집행에 유의하세요."
    risk = (
        f"⚠️ 리스크 경보: 하락 위험이 기준치를 초과했거나 데드크로스가 발생했습니다. {risk_action}"
        if status == "Declining" or ts_result.get("decline_risk", 0) >= 60
        else "현재 심각한 하락 위험이나 급격한 꺾임세는 감지되지 않았습니다."
    )

    # 5. 실행 제안 (Recommendation): ts_scorer의 동적 action_insight 그대로 적용
    recommendation = action_insight

    return {
        "summary": summary,
        "evidence": evidence,
        "drivers": drivers,             # NEW: 프론트엔드에 전달할 견인 요소
        "risk": risk,
        "recommendation": recommendation,
    }