# -*- coding: utf-8 -*-
"""feature_builder_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6OBtacVSl8-qzwxbhhnKEicE504U3g1
"""

import numpy as np
import pandas as pd

def normalize_0_100(series: pd.Series) -> pd.Series:
    values = pd.to_numeric(series, errors="coerce").fillna(0)
    min_value = values.min() if len(values) else 0
    max_value = values.max() if len(values) else 0

    if max_value == min_value:
        fill_value = 50 if max_value != 0 else 0
        return pd.Series([fill_value] * len(values), index=values.index, dtype=float)

    normalized = (values - min_value) / (max_value - min_value) * 100
    return normalized.fillna(0).clip(0, 100)

def safe_log1p(series: pd.Series) -> pd.Series:
    values = pd.to_numeric(series, errors="coerce").fillna(0)
    values = values.clip(lower=0)
    return np.log1p(values)

def build_trend_index(term_daily: pd.DataFrame, keyword_daily: pd.DataFrame) -> pd.DataFrame:
    """
    time_series_v4에서 정제한 'momentum'과 'c_l_ratio'를 바탕으로
    노이즈가 제거된 일별 최종 Trend Index를 산출합니다.
    """
    if keyword_daily.empty:
        return pd.DataFrame(columns=["date", "trend_index"])

    df = keyword_daily.copy().sort_values("date")

    # 💡 [퀀트 로직 적용]
    # 가속도(momentum)를 베이스로 하되, 화제성(c_l_ratio)을 가중치로 곱하여
    # 대중의 '진짜 관여도'가 폭발할 때 인덱스가 급등하도록 설계
    base_signal = df["momentum"] * (1 + (df["c_l_ratio"] / 100))

    # 로그 스케일링 후 0~100 정규화 (메가 유튜버 이상치 방어)
    df["trend_index"] = normalize_0_100(safe_log1p(base_signal))

    return df[["date", "trend_index"]].reset_index(drop=True)

def build_trend_features(
    keyword_daily: pd.DataFrame,
    weekly_partition: pd.DataFrame,
    trend_index: pd.DataFrame,
    analysis_options: dict | None = None,  # 💡 NEW: 분석 옵션 동적 수용
) -> dict:
    analysis_options = analysis_options or {}

    # 💡 [피드백 반영] 업종/성격에 따른 시계열 윈도우 동적 설정
    # F&B(외식) 등 단기 유행은 기존의 3일/7일 유지, 패션/IT 등 장기 트렌드는 14일/30일 등으로 확장
    trend_type = analysis_options.get("trend_type", "F&B")

    if trend_type == "F&B":
        short_span = 3
        long_span = 7
        window_size = 7
    else:  # 패션, IT, 일반 제조 등 장기 생명주기 업종
        short_span = 14
        long_span = 30
        window_size = 14  # 샤프 지수를 볼 최근 기간

    # 최소 데이터 요구량 방어 코드 수정
    if trend_index.empty or len(trend_index) < long_span:
        return empty_features()

    df = trend_index.sort_values("date").copy()
    ti_series = df["trend_index"].fillna(0)

    # 💡 1. 단기/장기 지수이동평균(EMA) 계산 (동적 Span 적용)
    short_ema = ti_series.ewm(span=short_span, adjust=False).mean()
    long_ema = ti_series.ewm(span=long_span, adjust=False).mean()

    # 현재와 직전(어제)의 EMA 값 추출
    curr_short, curr_long = short_ema.iloc[-1], long_ema.iloc[-1]
    prev_short, prev_long = short_ema.iloc[-2], long_ema.iloc[-2]

    # 💡 2. Crossover (변곡점) 판별 로직
    ema_cross = "none"
    if prev_short <= prev_long and curr_short > curr_long:
        ema_cross = "golden_cross" # 단기가 장기를 뚫고 올라감 (본격 상승 신호)
    elif prev_short >= prev_long and curr_short < curr_long:
        ema_cross = "death_cross"  # 단기가 장기 아래로 꺾임 (본격 하락 신호)

    # 💡 3. 트렌드 샤프 지수 (Trend Sharpe Ratio) - 밈(Meme) 필터링 (동적 Window 적용)
    recent_window = ti_series.tail(window_size)
    recent_mean = recent_window.mean()

    # 변동성(표준편차). 데이터가 너무 평탄해 0이 되는 것을 막기 위해 0.1(epsilon) 추가
    volatility = recent_window.std() + 0.1
    # 수익(성장률) 대비 리스크(변동성). 이 수치가 1.5 이상이면 매우 안정적인 우상향 트렌드
    sharpe_ratio = recent_mean / volatility

    # (기존 파이프라인 호환성을 위한 기본 지표들 - 동적 윈도우에 맞춤)
    previous_mean = ti_series.iloc[-(window_size * 2):-window_size].mean() if len(ti_series) >= (window_size * 2) else 0
    peak_trend_index = ti_series.max()
    decline_from_peak = ((peak_trend_index - curr_short) / peak_trend_index * 100) if peak_trend_index > 0 else 0

    return {
        "recent_mean": round(recent_mean, 4),
        "previous_mean": round(previous_mean, 4),
        "peak_trend_index": round(peak_trend_index, 4),
        "decline_from_peak": round(max(decline_from_peak, 0), 4),
        "volatility": round(volatility, 4),               # 변동성
        "sharpe_ratio": round(sharpe_ratio, 4),           # 트렌드 안정성
        "short_ema": round(curr_short, 4),                # 동적 단기 모멘텀
        "long_ema": round(curr_long, 4),                  # 동적 장기 모멘텀
        "ema_cross": ema_cross,                           # 골든/데드 크로스 상태
        "active_days": int((keyword_daily["mentions"] > 0).sum()),
        "weekly_rows": int(len(weekly_partition)),
    }

def empty_features() -> dict:
    return {
        "recent_mean": 0.0,
        "previous_mean": 0.0,
        "peak_trend_index": 0.0,
        "decline_from_peak": 0.0,
        "volatility": 0.0,
        "sharpe_ratio": 0.0,
        "short_ema": 0.0,
        "long_ema": 0.0,
        "ema_cross": "none",
        "active_days": 0,
        "weekly_rows": 0,
    }