# -*- coding: utf-8 -*-
"""time_series_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCqx790k39-VVcV6-AVR-kkKLBpxtWd0
"""

import numpy as np
import pandas as pd

# 💡 [피드백 반영 1] 플랫폼별 데이터 스케일 가중치 (Source Weight)
# 유튜브 조회수와 네이버 뉴스/블로그의 트래픽 규모 차이를 보정하기 위한 기준 매핑
SOURCE_WEIGHTS = {
    "youtube": 1.0,
    "naver_news": 0.3,  # 뉴스 조회/클릭 스케일 다운
    "naver_blog": 0.1,  # 블로그 조회/클릭 스케일 다운
    "instagram": 1.0,   # (추후 확장 대비)
}

def build_term_daily_metrics(
    filtered_raw: pd.DataFrame,
    analysis_options: dict | None = None  # NEW: 분석 옵션 수용
) -> pd.DataFrame:
    analysis_options = analysis_options or {}

    # 💡 [피드백 반영 2] 업종 성격에 따른 동적 트렌드 감쇠율(반감기) 설정
    trend_type = analysis_options.get("trend_type", "F&B")
    decay_rate = 0.15 if trend_type == "F&B" else 0.03  # F&B는 약 4.6일, 패션/IT는 약 23일 반감기

    columns = [
        "date",
        "source",
        "term",
        "term_type",
        "term_weight",
        "mentions",
        "weighted_mentions",
        "views",
        "likes",
        "comments",
        "engagements",
        "vpd",
        "momentum",
        "c_l_ratio",
    ]
    if filtered_raw.empty:
        return pd.DataFrame(columns=columns)

    df = filtered_raw.copy()
    df["date"] = pd.to_datetime(df["published_at"], errors='coerce').dt.date.astype(str)
    df["mention_unit"] = 1

    # Fractional Days: 초 단위 가속도 캐치
    published = pd.to_datetime(df["published_at"], utc=True).dt.tz_convert(None)
    collected = pd.to_datetime(df["collected_at"], utc=True).dt.tz_convert(None)

    age_days_exact = (collected - published).dt.total_seconds() / 86400.0
    age_days_exact = age_days_exact.clip(lower=0.01)

    # 💡 [피드백 반영 1 적용] 플랫폼별 가중치를 곱하여 스케일이 보정된 조회수 산출
    df["source_weight"] = df["source"].map(SOURCE_WEIGHTS).fillna(0.5)
    df["adjusted_views"] = df["views"] * df["source_weight"]

    # Time-Decay & 모멘텀 계산 시 보정된 조회수(adjusted_views) 사용
    df["time_decay_weight"] = np.exp(-decay_rate * age_days_exact)
    df["row_momentum"] = df["adjusted_views"] * df["time_decay_weight"]
    df["row_vpd"] = df["adjusted_views"] / age_days_exact

    # Source Isolation
    df["valid_likes"] = np.where(df["source"] == "youtube", df["likes"], 0)
    df["valid_comments"] = np.where(df["source"] == "youtube", df["comments"], 0)

    grouped = (
        df.groupby(["date", "source", "term", "term_type", "term_weight"], dropna=False)
        .agg(
            mentions=("mention_unit", "sum"),
            weighted_mentions=("term_weight", "sum"),
            views=("adjusted_views", "sum"),  # 스케일 보정된 조회수로 병합
            likes=("valid_likes", "sum"),
            comments=("valid_comments", "sum"),
            engagements=("engagements", "sum"),
            vpd=("row_vpd", "sum"),
            momentum=("row_momentum", "sum"),
        )
        .reset_index()
    )

    # Laplace Smoothing
    grouped["c_l_ratio"] = (grouped["comments"] / (grouped["likes"] + 1)) * 100

    return grouped[columns]


def build_keyword_set_daily_metrics(
    term_daily: pd.DataFrame,
    canonical_keyword: str,
    start_date: str | None = None,
    end_date: str | None = None,
    analysis_options: dict | None = None, # NEW: 분석 옵션 수용
) -> pd.DataFrame:
    analysis_options = analysis_options or {}
    trend_type = analysis_options.get("trend_type", "F&B")

    # 💡 [피드백 반영 3] 스파이크 방지용 이동평균(MA) 윈도우 동적 설정
    ma_window = 3 if trend_type == "F&B" else 7

    columns = [
        "date",
        "canonical_keyword",
        "mentions",
        "weighted_mentions",
        "views",
        "likes",
        "comments",
        "engagements",
        "vpd",
        "momentum",
        "c_l_ratio",
        "source_count",
        "core_mentions",
        "related_mentions",
    ]
    if term_daily.empty and not (start_date and end_date):
        return pd.DataFrame(columns=columns)
    if term_daily.empty:
        full_range = pd.date_range(start_date, end_date, freq="D")
        daily = pd.DataFrame({"date": full_range})
        daily["canonical_keyword"] = canonical_keyword
        for column in columns:
            if column not in daily.columns:
                daily[column] = 0
        daily["date"] = daily["date"].dt.date.astype(str)
        return daily[columns]

    df = term_daily.copy()
    df["core_mentions_part"] = df.apply(
        lambda row: row["mentions"] if row["term_type"] in ["canonical", "alias", "typo"] else 0,
        axis=1,
    )
    df["related_mentions_part"] = df.apply(
        lambda row: row["mentions"] if row["term_type"] == "related" else 0,
        axis=1,
    )

    daily = (
        df.groupby("date", dropna=False)
        .agg(
            mentions=("mentions", "sum"),
            weighted_mentions=("weighted_mentions", "sum"),
            views=("views", "sum"),
            likes=("likes", "sum"),
            comments=("comments", "sum"),
            engagements=("engagements", "sum"),
            vpd=("vpd", "sum"),
            momentum=("momentum", "sum"),
            source_count=("source", "nunique"),
            core_mentions=("core_mentions_part", "sum"),
            related_mentions=("related_mentions_part", "sum"),
        )
        .reset_index()
    )
    daily["canonical_keyword"] = canonical_keyword

    # 키워드 통합 레벨에서의 c_l_ratio 스무딩 재계산
    daily["c_l_ratio"] = (daily["comments"] / (daily["likes"] + 1)) * 100

    daily["date"] = pd.to_datetime(daily["date"])
    range_start = pd.to_datetime(start_date) if start_date else daily["date"].min()
    range_end = pd.to_datetime(end_date) if end_date else daily["date"].max()
    full_range = pd.date_range(range_start, range_end, freq="D")

    # 연속된 날짜로 Reindex
    daily = daily.set_index("date").reindex(full_range).rename_axis("date").reset_index()
    daily["canonical_keyword"] = canonical_keyword

    for column in columns:
        if column not in daily.columns:
            daily[column] = 0
    numeric_cols = [column for column in columns if column not in ["date", "canonical_keyword"]]
    daily[numeric_cols] = daily[numeric_cols].fillna(0)

    # 💡 [피드백 반영 3 적용] 결측치 채운 직후, 시계열 노이즈(스파이크) 완화를 위한 이동평균(MA) 적용
    # min_periods=1을 주어 초기 데이터가 NaN이 되는 것을 방지
    smoothing_cols = ["views", "likes", "comments", "engagements", "vpd", "momentum", "c_l_ratio"]
    daily[smoothing_cols] = daily[smoothing_cols].rolling(window=ma_window, min_periods=1).mean()

    daily["date"] = daily["date"].dt.date.astype(str)

    return daily[columns]


def build_weekly_partition(
    filtered_raw: pd.DataFrame,
    analysis_options: dict | None = None # NEW: 일관성을 위해 파라미터 추가
) -> pd.DataFrame:
    columns = [
        "week",
        "content_supply",
        "weighted_supply",
        "views",
        "comments",
        "engagements",
        "view_per_item",
        "engagement_per_item",
        "avg_velocity",
        "demand_pressure",
        "content_supply_z",
        "avg_velocity_z",
        "demand_pressure_z",
    ]
    if filtered_raw.empty:
        return pd.DataFrame(columns=columns)

    df = filtered_raw.copy()
    published = pd.to_datetime(df["published_at"], utc=True).dt.tz_convert(None)
    df["week"] = published.dt.to_period("W").apply(lambda value: value.start_time.date().isoformat())
    df["item_unit"] = 1

    collected = pd.to_datetime(df["collected_at"], utc=True).dt.tz_convert(None)
    age_days_exact = (collected - published).dt.total_seconds() / 86400.0
    age_days_exact = age_days_exact.clip(lower=0.01)

    # 💡 [피드백 반영 1 적용] 주간 파티션에서도 플랫폼 가중치 동일하게 적용
    df["source_weight"] = df["source"].map(SOURCE_WEIGHTS).fillna(0.5)
    df["adjusted_views"] = df["views"] * df["source_weight"]
    df["views_per_day"] = df["adjusted_views"] / age_days_exact

    weekly = (
        df.groupby("week", dropna=False)
        .agg(
            content_supply=("item_unit", "sum"),
            weighted_supply=("term_weight", "sum"),
            views=("adjusted_views", "sum"), # 보정된 조회수 기준
            comments=("comments", "sum"),
            engagements=("engagements", "sum"),
            avg_velocity=("views_per_day", "mean"),
        )
        .reset_index()
    )
    weekly["view_per_item"] = safe_divide(weekly["views"], weekly["content_supply"])
    weekly["engagement_per_item"] = safe_divide(weekly["engagements"], weekly["content_supply"])
    weekly["demand_pressure"] = safe_divide(weekly["avg_velocity"], weekly["content_supply"])
    weekly["content_supply_z"] = zscore(weekly["content_supply"])
    weekly["avg_velocity_z"] = zscore(weekly["avg_velocity"])
    weekly["demand_pressure_z"] = zscore(weekly["demand_pressure"])
    return weekly[columns]


def build_source_breakdown(filtered_raw: pd.DataFrame) -> list[dict]:
    if filtered_raw.empty:
        return []
    counts = filtered_raw.groupby("source").size().reset_index(name="count")
    total = counts["count"].sum()
    counts["ratio"] = counts["count"].apply(lambda count: round(count / total * 100, 1) if total else 0)
    return counts.sort_values("count", ascending=False).to_dict(orient="records")


def build_term_breakdown(filtered_raw: pd.DataFrame) -> list[dict]:
    if filtered_raw.empty:
        return []
    df = filtered_raw.copy()
    df["item_unit"] = 1
    grouped = (
        df.groupby(["term", "term_type"], dropna=False)
        .agg(count=("item_unit", "sum"), weighted_count=("term_weight", "sum"))
        .reset_index()
    )
    grouped["weighted_count"] = grouped["weighted_count"].round(2)
    return grouped.sort_values("weighted_count", ascending=False).to_dict(orient="records")


def safe_divide(numerator, denominator):
    return numerator.div(denominator.replace(0, pd.NA)).fillna(0)


def zscore(series: pd.Series) -> pd.Series:
    values = pd.to_numeric(series, errors="coerce").fillna(0)
    std = values.std()
    if not std or pd.isna(std):
        return pd.Series([0.0] * len(values), index=values.index)
    return ((values - values.mean()) / std).fillna(0)