# -*- coding: utf-8 -*-
"""ts_scorer_v5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUwT5LRkkZXAzac6HNigO9U3x18qO89l
"""

import math

def clip_0_100(value: float) -> float:
    if value is None or math.isnan(float(value)):
        return 0.0
    return max(0.0, min(100.0, float(value)))

def normalize_scalar_log1p(value: float, max_ref: float) -> float:
    value = max(0.0, float(value or 0))
    if max_ref <= 0:
        return 0.0
    return clip_0_100(math.log1p(value) / math.log1p(max_ref) * 100)

def calculate_growth_score(features: dict) -> float:
    recent_mean = float(features.get("recent_mean", 0) or 0)
    previous_mean = float(features.get("previous_mean", 0) or 0)
    coverage_ratio = clip_0_100(float(features.get("coverage_ratio", 0) or 0) * 100) / 100

    if previous_mean == 0 and recent_mean > 0:
        cold_start_score = 45 + min(recent_mean, 100) * 0.25 + min(coverage_ratio * 25, 25)
        return clip_0_100(min(cold_start_score, 70))
    if previous_mean == 0 and recent_mean == 0:
        return 0.0

    growth_rate = (recent_mean - previous_mean) / previous_mean
    base_score = 50 + (growth_rate * 25)
    return clip_0_100(base_score)

def calculate_reaction_score(features: dict) -> float:
    vpi = float(features.get("view_per_item", 0) or 0)
    epi = float(features.get("engagement_per_item", 0) or 0)
    vpi_score = normalize_scalar_log1p(vpi, 500000)
    epi_score = normalize_scalar_log1p(epi, 10000)
    return clip_0_100(vpi_score * 0.6 + epi_score * 0.4)

def calculate_saturation_score(features: dict) -> float:
    recent_mean = float(features.get("recent_mean", 0) or 0)
    peak = float(features.get("peak_trend_index", 0) or 0)
    if peak == 0:
        return 0.0
    return clip_0_100((recent_mean / peak) * 100)

def calculate_decline_risk(features: dict) -> float:
    decline_from_peak = float(features.get("decline_from_peak", 0) or 0)
    ema_cross = features.get("ema_cross", "none")
    risk = decline_from_peak
    if ema_cross == "death_cross":
        risk += 30
    return clip_0_100(risk)

def calculate_ts(
    features: dict,
    analysis_options: dict | None = None  # 💡 NEW: 업종 정보 수용
) -> dict:
    analysis_options = analysis_options or {}
    trend_type = analysis_options.get("trend_type", "F&B")

    growth_score = calculate_growth_score(features)
    reaction_score = calculate_reaction_score(features)
    saturation_score = calculate_saturation_score(features)
    decline_risk = calculate_decline_risk(features)

    ema_cross = features.get("ema_cross", "none")
    sharpe_ratio = float(features.get("sharpe_ratio", 0) or 0)
    previous_mean = float(features.get("previous_mean", 0) or 0)
    recent_mean = float(features.get("recent_mean", 0) or 0)
    decline_from_peak = float(features.get("decline_from_peak", 0) or 0)

    # 미세 노이즈 필터 (먼지 수준의 반응은 무시)
    is_meaningful_volume = recent_mean >= 3.0

    # 💡 [피드백 반영] 업종별 페이크 데드크로스 방어 임계치 동적 적용
    # 패션 등은 장기 트렌드이므로 15% 하락으로 꺾였다고 보지 않고 20%로 임계치 상향
    decline_threshold = 15.0 if trend_type == "F&B" else 20.0
    is_real_decline = (ema_cross == "death_cross") and (decline_from_peak > decline_threshold)

    # 국면(Regime) 판별 및 동적 가중치
    regime = "Watch"
    if is_real_decline or decline_risk > 60:
        regime = "Declining"
        w_growth, w_reaction, w_saturation, w_decline = 0.10, 0.20, 0.30, 0.40

    elif ema_cross == "golden_cross" and sharpe_ratio > 0.8 and is_meaningful_volume:
        regime = "Rising"
        w_growth, w_reaction, w_saturation, w_decline = 0.60, 0.25, 0.05, 0.10

    elif previous_mean < 1.0 and recent_mean > 3.0:
        regime = "Cold Start"
        w_growth, w_reaction, w_saturation, w_decline = 0.70, 0.30, 0.0, 0.0

    elif saturation_score > 80 and decline_from_peak <= decline_threshold:
        regime = "Hot"
        w_growth, w_reaction, w_saturation, w_decline = 0.20, 0.40, 0.30, 0.10

    else:
        regime = "Watch"
        w_growth, w_reaction, w_saturation, w_decline = 0.35, 0.30, 0.20, 0.15

    # 라이징 스타 보호 (상승장에서는 밈 페널티 면제)
    meme_penalty = 1.0
    if sharpe_ratio < 0.5 and recent_mean > 20 and regime not in ["Rising", "Cold Start"]:
        meme_penalty = 0.8

    raw_ts_score = (
        growth_score * w_growth
        + reaction_score * w_reaction
        + saturation_score * w_saturation
        + (100 - decline_risk) * w_decline
    )

    final_ts_score = raw_ts_score * meme_penalty

    # 💡 [피드백 반영] 업종(trend_type)을 넘겨주어 동적인 액션 문구 생성
    action_insight = generate_business_action(regime, sharpe_ratio, meme_penalty, trend_type)

    return {
        "ts_score": round(clip_0_100(final_ts_score), 1),
        "status_label": regime,
        "action_insight": action_insight,
        "growth_score": round(growth_score, 1),
        "reaction_score": round(reaction_score, 1),
        "saturation_score": round(saturation_score, 1),
        "decline_risk": round(decline_risk, 1),
        "formula_version": "TS_v5.0_Dynamic_Regime", # 버전 업데이트
    }

def generate_business_action(
    regime: str,
    sharpe_ratio: float,
    meme_penalty: float,
    trend_type: str = "F&B" # 💡 NEW: 텍스트 분기 처리
) -> str:

    # 공통 밈 페널티 경고
    if meme_penalty < 1.0:
        return "⚠️ [리스크 경고] 조회수는 높지만 변동성이 극심한 '단기 밈(Meme)'입니다. 대규모 예산 투입보다는 1회성 마케팅 소재로만 활용하세요."

    # 업종별 문구 세팅 (F&B vs 일반/패션/IT)
    is_fb = (trend_type == "F&B")

    if regime == "Rising":
        if is_fb:
            return "🚀 [도입 강력 추천] 단기 모멘텀이 장기 모멘텀을 돌파했습니다(골든크로스). 이번 주말 신메뉴로 적극 도입하여 선점 효과를 누리세요."
        return "🚀 [기획 강력 추천] 상승 추세가 뚜렷합니다. 관련 상품 기획이나 초기 발주 물량을 늘려 시장 수요에 선제적으로 대응하세요."

    elif regime == "Hot":
        if is_fb:
            return "🔥 [유지 전략] 트렌드가 정점에서 안정적으로 소비되고 있습니다. 기존 메뉴를 유지하되 식자재 재고를 넉넉히 확보하세요."
        return "🔥 [캐시카우 유지] 트렌드가 정점에서 안정화되었습니다. 프로모션을 통해 판매량을 극대화하고, 재고 회전율 관리에 집중하세요."

    elif regime == "Declining":
        if is_fb:
            return "📉 [출구 전략] 꺾임세(데드크로스)가 발생했습니다. 신규 발주를 중단하고 기존 재고 소진을 위한 할인 프로모션을 기획하세요."
        return "📉 [비중 축소] 하락장으로 접어들고 있습니다. 신규 제품 라인업 투입을 멈추고 기존 물량 털어내기(세일)에 돌입하세요."

    elif regime == "Cold Start":
        if is_fb:
            return "🌱 [테스트 권장] 이제 막 반응이 오기 시작했습니다. 소량의 샘플을 매장 내 무료 테이스팅으로 제공해 고객 반응을 간보세요."
        return "🌱 [마이크로 테스트] 초기 바이럴 조짐이 보입니다. 소규모 시범 판매나 랜딩 페이지 A/B 테스트를 통해 타겟의 반응을 점검하세요."

    else:
        return "👀 [관망] 아직 방향성을 확신할 뚜렷한 추세가 없습니다. 무리한 기획보다는 지표의 변화를 조금 더 지켜보는 것을 권장합니다."